// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAK3TFFj3axNjVbVrd2fpy-q-m6Y0dgrB4',
    appId: '1:76576206822:web:e979c53943b7ea69937027',
    messagingSenderId: '76576206822',
    projectId: 'planup-9835f',
    authDomain: 'planup-9835f.firebaseapp.com',
    storageBucket: 'planup-9835f.appspot.com',
    measurementId: 'G-54HMZ0R5CL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwikEJTiHdi7szdjR0hxqKznQsXk4VVOQ',
    appId: '1:76576206822:android:3e0cdf1f607b9cbb937027',
    messagingSenderId: '76576206822',
    projectId: 'planup-9835f',
    storageBucket: 'planup-9835f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkX1acAGcOU1hjwXXDophpFeB-E_34S0E',
    appId: '1:76576206822:ios:753637f298d8de36937027',
    messagingSenderId: '76576206822',
    projectId: 'planup-9835f',
    storageBucket: 'planup-9835f.appspot.com',
    iosBundleId: 'com.planup.planupp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkX1acAGcOU1hjwXXDophpFeB-E_34S0E',
    appId: '1:76576206822:ios:4531f6002311de40937027',
    messagingSenderId: '76576206822',
    projectId: 'planup-9835f',
    storageBucket: 'planup-9835f.appspot.com',
    iosBundleId: 'com.planup.planupp.RunnerTests',
  );
}
